### ISSUE TITLE
Enable Travis CI build for project

### ISSUE THREAD

**Issue by whymarrh** [CodeNL/CodeNL.github.io#4]
CI builds should be enabled before pull requests are made to facilitate automation. This should mostly be a matter of adding a Travis config and flipping the switch on the Travis website.

**Comment by whymarrh** [comment]
@Gudahtt do you want to enable this? I can't seem to sign into Travis CI.

**Comment by Gudahtt** [comment]
@whymarrh Sure, no problem. Done.

I've also enabled "Build only if .travis.yml is present".
